In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from skimage.io import imread
from skimage.transform import resize
import os

In [2]:
datadir='train3/'
images = []
labels = []
for i in os.listdir(datadir):
    img_path = os.path.join(datadir,i)
    img = imread(img_path)
    img_resized = resize(img, (64,64))
    images.append(img_resized.flatten())  # Flatten the image
    # labels.append(label)
    if 'cat' in i:
        labels.append(0)
    if 'dog' in i:
        labels.append(1)

labels = np.array(labels)
images = np.array(images)


In [3]:
print(images)

[[0.81046104 0.6575167  0.35555513 ... 0.00857414 0.0087858  0.00091144]
 [0.15303416 0.17015273 0.16498222 ... 0.17959339 0.13056525 0.10397594]
 [0.13208536 0.1565743  0.18784104 ... 0.7146657  0.6997991  0.03091452]
 ...
 [0.39054698 0.36614849 0.36990648 ... 0.70269385 0.65767618 0.65821151]
 [0.70758253 0.52534049 0.39177951 ... 0.58921256 0.41136542 0.31929561]
 [0.69803922 0.69803922 0.69803922 ... 0.631457   0.40400602 0.07459426]]


In [4]:
df=pd.DataFrame(images)
df['labels']=labels
df.head()

0         1         2         3         4         5         6  \
0  0.810461  0.657517  0.355555  0.835218  0.680625  0.378251  0.867515   
1  0.153034  0.170153  0.164982  0.169443  0.182440  0.202955  0.166240   
2  0.132085  0.156574  0.187841  0.155844  0.178066  0.224885  0.172808   
3  0.869714  0.873635  0.854028  0.874746  0.878602  0.859267  0.893177   
4  0.278082  0.991807  0.995726  0.278388  0.992114  0.996021  0.283545   

          7         8         9  ...     12279     12280     12281     12282  \
0  0.701230  0.395934  0.888483  ...  0.008779  0.009194  0.000911  0.008772   
1  0.181175  0.188083  0.140840  ...  0.307866  0.237933  0.222727  0.265270   
2  0.196264  0.238614  0.190877  ...  0.693014  0.662776  0.055816  0.744480   
3  0.894221  0.889057  0.902053  ...  0.849043  0.858320  0.858257  0.847114   
4  0.996895  0.999205  0.291805  ...  0.615676  0.915650  0.889626  0.540798   

      12283     12284     12285     12286     12287  labels  
0  0.009181  0.000911  0.008574  0.008786  0.000911       0  
1  0.199728  0.178419  0.179593  0.130565  0.103976       0  
2  0.737745  0.014604  0.714666  0.699799  0.030915       0  
3  0.844590  0.837848  0.846790  0.831655  0.817268       0  
4  0.872180  0.853323  0.499543  0.808683  0.793762       0  

[5 rows x 12289 columns]

In [5]:
y=df.labels
x=df.drop("labels",axis=1)

In [6]:
y

0      0
1      0
2      0
3      0
4      0
      ..
245    1
246    1
247    1
248    1
249    1
Name: labels, Length: 250, dtype: int32

In [7]:
x

0         1         2         3         4         5         6      \
0    0.810461  0.657517  0.355555  0.835218  0.680625  0.378251  0.867515   
1    0.153034  0.170153  0.164982  0.169443  0.182440  0.202955  0.166240   
2    0.132085  0.156574  0.187841  0.155844  0.178066  0.224885  0.172808   
3    0.869714  0.873635  0.854028  0.874746  0.878602  0.859267  0.893177   
4    0.278082  0.991807  0.995726  0.278388  0.992114  0.996021  0.283545   
..        ...       ...       ...       ...       ...       ...       ...   
245  0.024481  0.051427  0.064722  0.010632  0.019441  0.038318  0.011678   
246  0.426148  0.305052  0.090180  0.465418  0.347636  0.098614  0.510658   
247  0.390547  0.366148  0.369906  0.392762  0.382448  0.399013  0.418161   
248  0.707583  0.525340  0.391780  0.710645  0.530510  0.393530  0.722635   
249  0.698039  0.698039  0.698039  0.698039  0.698039  0.698039  0.698039   

        7         8         9      ...     12278     12279     12280  \
0    0.701230  0.395934  0.888483  ...  0.000933  0.008779  0.009194   
1    0.181175  0.188083  0.140840  ...  0.181531  0.307866  0.237933   
2    0.196264  0.238614  0.190877  ...  0.206417  0.693014  0.662776   
3    0.894221  0.889057  0.902053  ...  0.809736  0.849043  0.858320   
4    0.996895  0.999205  0.291805  ...  0.913541  0.615676  0.915650   
..        ...       ...       ...  ...       ...       ...       ...   
245  0.022279  0.041886  0.015754  ...  0.187513  0.160776  0.174728   
246  0.377086  0.119333  0.549457  ...  0.259883  0.455650  0.373297   
247  0.413702  0.436921  0.416287  ...  0.719844  0.737520  0.703248   
248  0.561288  0.407964  0.652555  ...  0.356279  0.755049  0.584328   
249  0.698039  0.698041  0.697692  ...  0.070565  0.632057  0.403615   

        12281     12282     12283     12284     12285     12286     12287  
0    0.000911  0.008772  0.009181  0.000911  0.008574  0.008786  0.000911  
1    0.222727  0.265270  0.199728  0.178419  0.179593  0.130565  0.103976  
2    0.055816  0.744480  0.737745  0.014604  0.714666  0.699799  0.030915  
3    0.858257  0.847114  0.844590  0.837848  0.846790  0.831655  0.817268  
4    0.889626  0.540798  0.872180  0.853323  0.499543  0.808683  0.793762  
..        ...       ...       ...       ...       ...       ...       ...  
245  0.185587  0.135122  0.146950  0.166305  0.141025  0.152789  0.172397  
246  0.267415  0.461516  0.379162  0.273283  0.464922  0.382501  0.276824  
247  0.696497  0.707439  0.676280  0.667922  0.702694  0.657676  0.658212  
248  0.398614  0.717246  0.524020  0.373870  0.589213  0.411365  0.319296  
249  0.074606  0.631171  0.403712  0.074320  0.631457  0.404006  0.074594  

[250 rows x 12288 columns]

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [9]:
svm = SVC(kernel='linear')  # You can experiment with other kernels like 'rbf'
svm.fit(x_train, y_train)

SVC(kernel='linear')

In [10]:
y_pred = svm.predict(x_test)
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')


Accuracy: 0.58


In [11]:
from sklearn.model_selection import GridSearchCV

In [12]:
param_grid = {
    'C': [10, 20, 50],
    'kernel': ['poly', 'rbf']
}
GCV = GridSearchCV(SVC(kernel="poly"),param_grid,return_train_score=False)
GCV.fit(x_train,y_train)

GridSearchCV(estimator=SVC(kernel='poly'),
             param_grid={'C': [10, 20, 50], 'kernel': ['poly', 'rbf']})

In [13]:
GCV.best_params_

{'C': 10, 'kernel': 'poly'}

In [14]:
GCV.best_score_

0.585

In [15]:
best_estimator=GCV.best_estimator_
y_pred = best_estimator.predict(x_test)
accuracy_score(y_test, y_pred)

0.6